---
title: "R Notebook"
output: html_notebook
---


```{r}
rm(list=ls())
source('./simulation_functions.R')
registerDoParallel(13)
```




```{r}
num_patients = c(500)
biomarker_effect = c(-1.5,0, 1.5)
biomarker_prevalence = c(0.1,0.3, 0.5)
biomarker_gamma = c(-0.3,0.0,0.3)
pre_genotyping_proportion = c(0.0, 0.4, 0.8)
pop_mort_baseline_hazard = c(0.02, 0.04, 0.06)
pop_mort_gamma = c(-0.3, 0, 0.3)
pop_genomic_baseline_hazard = c(0.05, 0.15, 0.25)
pop_genomic_gamma = c(-0.3, 0, 0.3)
genomic_sd = c(1,2)
random_genomic_delta = c(0.5,1.0)
patient_mort_hazard_std_dev = c(1,2)
patient_mort_hazard_random_delta = c(0.5, 1.0)
patient_testing_hazard_multiplier = c(0,2)
patient_testing_hazard_multiplier_increasing = c(0,1)
progression_hazard_logit_mean = c(0.5,1,2)
progression_hazard_std_dev = c(1,2)
right_censor_hazard = c(0.01, 0.1)
informed_right_censoring = c(0,1)
observation_prob = c(0.5, 0.75)
informative_observation_multiplier = c(0, 1)


parameter_frame = expand.grid(list(num_patients = num_patients,
                                   biomarker_effect=biomarker_effect, 
                                   biomarker_gamma = biomarker_gamma,
                                   biomarker_prevalence=biomarker_prevalence, 
                                   pre_genotyping_proportion=pre_genotyping_proportion,
                                   pop_mort_baseline_hazard=pop_mort_baseline_hazard,
                                   pop_mort_gamma=pop_mort_gamma,
                                   pop_genomic_baseline_hazard = pop_genomic_baseline_hazard,
                                   pop_genomic_gamma = pop_genomic_gamma,
                                   genomic_sd = genomic_sd,
                                   random_genomic_delta = random_genomic_delta,
                                   patient_mort_hazard_std_dev=patient_mort_hazard_std_dev, 
                                   patient_mort_hazard_random_delta=patient_mort_hazard_random_delta, 
                                   patient_testing_hazard_multiplier=patient_mort_hazard_random_delta, 
                                   patient_testing_hazard_multiplier_increasing=patient_testing_hazard_multiplier_increasing,
                                   progression_hazard_std_dev=progression_hazard_std_dev, 
                                   right_censor_hazard=right_censor_hazard, 
                                   informed_right_censoring=informed_right_censoring, 
                                   observation_prob=observation_prob,
                                   informative_observation_multiplier=informative_observation_multiplier))


```



```{r}

# If sample  
#thesample = sample(nrow(parameter_frame), 100000, replace=FALSE)
#parameter_frame = parameter_frame[thesample,]

# first half
#parameter_frame = parameter_frame[1:(nrow(parameter_frame)/2), ]

split <- parameter_frame %>% group_split(group_id = row_number() %/% 100000)
rm(parameter_frame)

oldw <- getOption("warn")
options(warn = -1)

for (j in 1:length(split)){
      thesplit <- split[[j]] %>% ungroup() %>% select(-group_id)
      argslist = lapply(as.list(1:dim(thesplit)[1]), function(x) as.list(thesplit[x[1],]))

      results = foreach(i = c(1:length(argslist)), .export=ls(.GlobalEnv), .packages=c('dplyr','foreach','survival')) %dopar% {
    
          temp = do.call(simulate_single_cohort, argslist[[i]])
          bind_rows(bind_cols(thesplit[i,], as_tibble(eval_differences_naive(temp$true_cohort, temp$observed_cohort)) %>% mutate(strategy='naive')), 
               bind_cols(thesplit[i,], as_tibble(eval_differences_left_trunc(temp$true_cohort, temp$observed_cohort)) %>% mutate(strategy='left_trunc')), 
               bind_cols(thesplit[i,], as_tibble(eval_differences_post_testing_only(temp$true_cohort, temp$observed_cohort)) %>% mutate(strategy='post_test')),
               bind_cols(thesplit[i,], as_tibble(eval_differences_left_trunc_timetotest_covariate(temp$true_cohort, temp$observed_cohort)) %>% mutate(strategy='left_trunc_timetotest_covariate')),
               bind_cols(thesplit[i,], as_tibble(eval_differences_left_trunc_timetotest_andrisk_covariate(temp$true_cohort, temp$observed_cohort)) %>% mutate(strategy='left_trunc_timetotestandrisk_covariate')))
      }
        
        results = bind_rows(results)
        
        write_csv(results, paste0("./sims/sim_",j,".csv"))
        print(j)
}

options(warn = oldw)

```










