---
title: "R Notebook"
output: html_notebook
---


```{r}
library(survival)
library(survminer)
library(dplyr)
library(SurvCorr)
library(tranSurv)
library(foreach)
library(doParallel)
rm(list=ls())
registerDoParallel(detectCores() - 2)
```


```{r}
# ok. events we care about:
# 1) mortality
# 2) testing
# 3) progression
# 4) right censoring
# 5) observation
```

```{r}
logit <- function(x){log(x/(1-x))}

sigmoid <- function(x) {
   1 / (1 + exp(-x))
}
```


```{r}

pop_hazard_mort_func <- function(t){
  # constant hazard or exponential distribution for survival
  hazard = 0.02

  
  # weibull
  #lambda = 0.05
  #p = 0.1
  #hazard = p * lambda^p * t^(p-1)
  
  #hazard = min(1, 0.1 * sqrt(t))
  
  return(hazard)
  
}


pop_hazard_genomic_func <- function(t){
  hazard = 0.25
  return(hazard)
}

create_patient_mort_hazard_vector <- function(max_time, std_dev, population_hazard_func, biomarker, biomarker_mult, random_delta){
  diff_vector <- vector()
  diff_vector[1] <- rnorm(1,mean=0, sd=std_dev)
  for(i in 2:max_time){
    updown = ifelse(rbinom(1,1,0.5)==1, 1, -1)
    diff_vector[i] = diff_vector[i-1] + updown*random_delta
  }

  
  prob_morts = sapply(1:max_time, population_hazard_func)
  pop_vector = logit(prob_morts)
  
  
  output_logits = pop_vector + diff_vector + biomarker*biomarker_mult
  output_probs = sigmoid(output_logits)
  return(output_probs)
  
}


create_progression_hazard_vector <- function(std_dev, mort_hazard_vector){
  return(sigmoid(logit(mort_hazard_vector) + rnorm(1,mean=1,sd=std_dev)))
}





create_patient_testing_hazard_vector <- function(max_time, multiplier, patient_mort_hazard_vector, population_hazard_genomic_func){
  
  # output_vector <- vector()
  # for(i in 1:max_time){
  #   output_vector[i] = sigmoid(logit(population_hazard_genomic_func(i)) + multiplier*logit(patient_mort_hazard_vector[i]) )
  # }
  

  output_vector <- sapply(1:max_time, function(i) sigmoid(logit(population_hazard_genomic_func(i)) + multiplier*logit(patient_mort_hazard_vector[i])))
  
  return(output_vector)
}


create_patient_right_censoring_hazard_vector <- function(right_censor_hazard = 0.05, max_time){
  hazard = right_censor_hazard
  return(rep(hazard, max_time))
}

create_patient_observation_vector <- function(observed_proba = 0.1, mort_hazard_vector){
  # could make observation a function of mortality risk but for now will not
  observed_prob = observed_proba
  prelim = rep(observed_prob, length(mort_hazard_vector))
  # always observe last month for now
  prelim[length(mort_hazard_vector)] = 1
  return(prelim)
}

```

```{r}
simulate_single_cohort <- function(num_patients=10000, len_follow_up=60, biomarker_effect = 2, biomarker_prevalence = 0.3,
                                   patient_mort_hazard_std_dev = 2, patient_mort_hazard_random_delta = 1,
                                   patient_testing_hazard_multiplier = 2, 
                                   progression_hazard_std_dev = 1,
                                   right_censor_hazard = 0.05,
                                   observation_prob = 0.1,
                                   popul_hazard_mort_func = pop_hazard_mort_func,
                                   popul_hazard_genomic_func = pop_hazard_genomic_func){
  
  
  # biomarker prevalence 0.3
  biomarker = rbinom(num_patients, 1, biomarker_prevalence)
  biomarker_mult = biomarker_effect
  
  results = foreach(i = 1:num_patients) %do% {
  results = list(10)
  
  # risks
  # mortality hazard
  results[[1]] = create_patient_mort_hazard_vector(len_follow_up, std_dev = patient_mort_hazard_std_dev, popul_hazard_mort_func, biomarker[i], biomarker_mult, random_delta = patient_mort_hazard_random_delta)
  
  # testing hazard
  results[[2]] = create_patient_testing_hazard_vector(len_follow_up, multiplier = patient_testing_hazard_multiplier, results[[1]], popul_hazard_genomic_func)
  
  # progression hazard
  results[[3]] = create_progression_hazard_vector(progression_hazard_std_dev, results[[1]])
  
  # right censoring hazard
  results[[4]] = create_patient_right_censoring_hazard_vector(right_censor_hazard, len_follow_up)
  
  # observation hazard
  results[[5]] = create_patient_observation_vector(observation_prob, results[[1]])
  
  # events
  
  for(i in 1:5){
    results[[i+5]] = sapply(results[[i]], function(x){rbinom(1,1,x)})

  }
  
  # observation times
  results[[11]] = which(results[[10]] == 1)
  
  
  # results[[12]] survival times

  # results[[13]] death indicator
  # 14 testing time
  # 15 testing indicator
  # 16 progression times
  # 17 progression indicator
  # 18 right censor times
  # 19 right censor indicator
  
  j = 1
  for(i in c(1,3,5,7)){
    
    results[[i+11]] = ifelse(sum(results[[j+5]]) > 0, which.max(results[[j+5]]), NA)
    results[[i+12]] = ifelse(is.na(results[[i+11]]), 0, 1)
    results[[i+11]] = ifelse(results[[i+12]] == 0, len_follow_up, results[[i+11]])
    j = j + 1
    
  }

  results
}

# get vector of survival times across cohort
survival_times <- sapply(results, function(x) x[[12]])
died <- sapply(results, function(x) x[[13]])
testing_times <- sapply(results, function(x) x[[14]])
tested <- sapply(results, function(x) x[[15]])
progression_times <- sapply(results, function(x) x[[16]])
progressed <- sapply(results, function(x) x[[17]])
right_censor_times <- sapply(results, function(x) x[[18]])
right_censored <- sapply(results, function(x) x[[19]])

patient_obs_times <- lapply(results, function(x) x[[11]])



result = data.frame(cbind(biomarker, survival_times, died, testing_times, tested, progression_times, progressed, right_censor_times, right_censored)) %>% mutate(pfs_times = pmin(progression_times, survival_times)) %>% mutate(pfs_event = ifelse(died==0 & pfs_times == len_follow_up, 0, 1))
  
return(list(results, patient_obs_times, result))

}
                                   
```

```{r}
cohort = simulate_single_cohort()
result = cohort[[3]]
patient_obs_times = cohort[[2]]
```


```{r}



survfit <- surv_fit(Surv(survival_times, died) ~ 1, data = result)
ggsurvplot(survfit, xlim=c(0,36), risk.table=TRUE, title='OS, true cohort')


survfit <- surv_fit(Surv(pfs_times, pfs_event) ~ 1, data = result)
ggsurvplot(survfit, xlim=c(0,36), risk.table=TRUE, title='PFS, true cohort')


survfit <- surv_fit(Surv(survival_times, died) ~ biomarker, data = result)
ggsurvplot(survfit, xlim=c(0,36), risk.table=TRUE, title='OS, true cohort')


print(summary(coxph(Surv(survival_times, died) ~ biomarker, data = result)))





```





```{r}
result <- result %>% mutate(observed = ifelse(tested == 1 & (survival_times >= testing_times), TRUE, FALSE))
observed_obs_times <- patient_obs_times[result$observed]
observed <- result %>% filter(observed==TRUE)

# deal with informative right censoring
informed_right_censoring = 0
if(informed_right_censoring==0){
  observed <- observed %>% mutate(progression_times = ifelse(right_censored == 1 & right_censor_times < progression_times, right_censor_times, progression_times)) %>% mutate(progressed = ifelse(right_censored == 1 & progression_times == right_censor_times, 0, progressed)) %>% mutate(survival_times = ifelse(right_censored == 1 & right_censor_times < survival_times, right_censor_times, survival_times)) %>% mutate(died = ifelse(right_censored == 1 & survival_times == right_censor_times, 0, died))
} else {
    observed <- observed %>% mutate(progression_times = ifelse(right_censored == 1 & right_censor_times < progression_times, right_censor_times, progression_times)) %>% mutate(progressed = ifelse(right_censored == 1 & progression_times == right_censor_times, 0, progressed)) %>% mutate(survival_times = ifelse(died==0 & right_censored == 1 & right_censor_times < survival_times, right_censor_times, survival_times)) 

}


# adjust progression time based on observation time
for(i in 1:nrow(observed)){
  if(observed[i,]$progressed == 1){
    obs_times = observed_obs_times[[i]]
    observed[i,]$progression_times = obs_times[obs_times >= observed[i,]$progression_times][1]
  }
}



observed <- observed %>% mutate(pfs_times = pmin(survival_times, progression_times)) %>% mutate(pfs_event = ifelse(progressed==1 | died == 1, 1, 0))



# method that incorporates immortal time, which generally is bad but can sometimes lead to less biased estimates here
survfit <- surv_fit(Surv(survival_times, died) ~ 1, data = observed)
ggsurvplot(survfit, xlim=c(0,36), title='Observed OS with immortal time', risk.table=TRUE)

survfit <- surv_fit(Surv(survival_times, died) ~ biomarker, data = observed)
ggsurvplot(survfit, xlim=c(0,36), title='Observed OS with immortal time', risk.table=TRUE)

# biomarker calculation
summary(coxph(Surv(survival_times, died) ~ biomarker, data = observed))

survfit <- surv_fit(Surv(pfs_times, pfs_event) ~ biomarker, data = observed)
ggsurvplot(survfit, xlim=c(0,36), title='Observed PFS with immortal time', risk.table=TRUE)

survfit <- surv_fit(Surv(pfs_times, pfs_event) ~ 1, data = observed)
ggsurvplot(survfit, xlim=c(0,36), title='Observed PFS with immortal time', risk.table=TRUE)


# method that would yield appropriate left trunc if no assoc with death
survfit <- surv_fit(Surv(testing_times, survival_times, died) ~ 1, data = observed)
ggsurvplot(survfit, xlim=c(0,36), title='Observed OS with standard left trunc', risk.table=TRUE)


survfit <- surv_fit(Surv(testing_times, survival_times, died) ~ biomarker, data = observed)
ggsurvplot(survfit, xlim=c(0,36), title='Observed OS with standard left trunc', risk.table=TRUE)

# biomarker calculation
summary(coxph(Surv(testing_times, survival_times, died) ~ biomarker , data = observed))


```


```{r}
# calculate conditional Kendall's tau to check for informative left truncation
cKendall(observed$testing_times, observed$survival_times, observed$died)
```
